import React from "react"

const TermsOfService = () =>{
    return (
        <div>
            <h1>Terms of Service</h1>
            <p>Last updated: April 24, 2020</p>
            <h2>Introduction</h2>
            <p>NestQ, collectively known as the "Site" or "website", provides tools and content for people interested in portfolio construction and analytics. Nothing on nestq.com, or any page within the nestq.com domain should be considered an offering or recommendation of securities or financial advice. This website is made available for educational and entertainment purposes only. Please read the following important terms and conditions ("Terms of Service") carefully. These Terms of Service govern your access to and use of the Site. This is a legal agreement between you and Abdennour. YOU UNDERSTAND THAT BY USING THE SITE, OR YOUR ACCOUNT, YOU ARE AGREEING TO BE BOUND BY THESE TERMS OF SERVICE. IF YOU DO NOT ACCEPT THESE TERMS OF SERVICE IN THEIR ENTIRETY, OR ANY SUBSEQUENT MODIFICATIONS THERETO, YOU MAY NOT ACCESS OR USE THE SITE.</p>

            <h2>Your Acceptance</h2>
            <p>Your use of the site is subject to this Terms of Service Agreement and the current Privacy Policy published at https://www.nestq.ca/privacy-policy. Each time you use the Site, you agree to be bound by the following Terms of Service and our Privacy Policy. If you do not agree to all of these conditions, then you must immediately discontinue your use of the Site. I may at any time revise or amend these Terms of Service, and it is your responsibility to review the Terms of Service for any changes each time you visit the Site. Your use of the Site following any revision or amendment of these Terms of Service will signify your assent to and acceptance of the revised Terms of Service. These Terms of Service apply to all customers, visitors, users, and others who view the Site ("Users").</p>
            <h2>Information Disclaimer</h2>
            <p>The Site may provide certain financial market data, research and other financial information (collectively "Information") that has been independently obtained by certain financial market information services and other providers (collectively the "Information Providers"). All data and Information is provided "as is" and the Information is intended solely as general information for educational and entertainment purposes only and is neither professional advice for any investment nor a substitute for other professional advice and services from qualified financial services providers familiar with your financial situation. Decisions based on Information contained within the Site are your sole responsibility. Always seek the advice of your financial advisor or other qualified financial services provider regarding any investment. The Information is provided with the understanding that NestQ is not engaged in rendering professional services or advice, and is not a registered investment advisor. Your use of the Site is subject to this disclaimer: Abdennour assumes no responsibility for any consequences relating directly or indirectly to any action or inaction you take based on the Information or other material on this Site. NestQ does not guarantee or certify the accuracy, completeness, timeliness, or correct sequencing of the Information made available, the Information Providers, or any other third party transmitting the Information (the "Information Transmitters"). You agree that NestQ, the Information Providers, and the Information Transmitters shall not be liable in any way for the accuracy, completeness, timeliness, or correct sequencing of the Information, or for any decision made or action taken by you relying upon the Information. You further agree that NestQ, the Information Providers, and the Information Transmitters will not be liable in any way for the interruption or cessation in the providing of any data, Information, or other aspect of the Site. </p>
            <h2>Warranty Disclaimer</h2>
            <p>THE INFORMATION PROVIDED THROUGH THE SITE IS PROVIDED "AS IS" AND "AS AVAILABLE." YOU AGREE THAT YOUR USE OF THE SITE SHALL BE AT YOUR SOLE RISK. NESTQ MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY, ADEQUACY, TIMELINESS, OR COMPLETENESS OF THIS SITE'S CONTENT AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, OMISSIONS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION, DELAY OR CESSATION OF TRANSMISSION TO OR FROM THE SITE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE SITE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SITE. NESTQ PROVIDES NO GUARANTEE AGAINST THE POSSIBILITY OF DELETION, MIS-DELIVERY OR FAILURE TO STORE COMMUNICATIONS, PERSONALIZED SETTINGS, OR OTHER DATA. </p>
            <h2>Limitation of Liability</h2>
            <p>IN NO EVENT SHALL ABDENNOUR BE LIABLE TO YOU FOR ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE SITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE SITE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH THE SITE BY ANY THIRD PARTY, (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT, (VI) YOUR USE, OR INABILITY TO USE, ANY PORTION OF THE SITE OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE SITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION. </p>
            <h2>Indemnity</h2>
            <p> You agree to indemnify and hold Abdennour harmless from any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the Site; (ii) your violation of any term of these Terms of Service; (iii) your violation of any third party right, including without limitation any copyright, property, or privacy right. This defense and indemnification obligation will survive termination of these Terms of Service or discontinuance of your use of the Site.</p>        
            <h2>Ability to Accept</h2>
            <p>By your use of the Site, you affirm that you are either are at least 18 years of age, or an emancipated minor, or possess legal parental or guardian consent, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service. In any case, you affirm that you are 13 years old or older, as the Site is not intended for children under that age of 13. If you are under 13 years of age, do not use the Site.</p>
            <h2>Terms and Termination</h2>
            <p>Your permission to access the Site under these Terms of Service will immediately terminate if you fail to comply with any term or condition. Upon such violation, you agree to terminate access to the Site. </p>
        </div>
    )
}

export default TermsOfService;